#!/usr/bin/env python3
"""Apply dynamic UINT8 Conv quantization to a Nemotron encoder ONNX graph.

This mirrors the broad strategy used by the sherpa-onnx int8 export: Conv
weights become UINT8 initializers, activations are dynamically quantized, and
Conv nodes become ConvInteger plus the float scale/bias tail generated by
ONNX Runtime's quantizer.
"""
from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path

import onnx
from onnxruntime.quantization import QuantType, quantize_dynamic


def quant_type(value: str) -> QuantType:
    match value:
        case "quint8":
            return QuantType.QUInt8
        case "qint8":
            return QuantType.QInt8
        case _:
            raise argparse.ArgumentTypeError(f"unsupported quant type: {value}")


def op_counts(path: Path) -> Counter[str]:
    model = onnx.load(path, load_external_data=False)
    return Counter(node.op_type for node in model.graph.node)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--weight-type",
        type=quant_type,
        default=QuantType.QUInt8,
        help="Conv weight quantization type. Default: quint8.",
    )
    parser.add_argument(
        "--per-channel",
        action="store_true",
        help="Use per-output-channel Conv weight quantization instead of sherpa-style per-tensor quantization.",
    )
    args = parser.parse_args()

    before = op_counts(args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    quantize_dynamic(
        args.input,
        args.output,
        op_types_to_quantize=["Conv"],
        per_channel=args.per_channel,
        weight_type=args.weight_type,
        use_external_data_format=False,
    )
    onnx.checker.check_model(str(args.output))
    after = op_counts(args.output)
    print(
        f"[quantize] wrote {args.output} "
        f"Conv {before.get('Conv', 0)}->{after.get('Conv', 0)} "
        f"ConvInteger {before.get('ConvInteger', 0)}->{after.get('ConvInteger', 0)} "
        f"weightType={args.weight_type.name} perChannel={args.per_channel}"
    )


if __name__ == "__main__":
    main()
